frescobaldi/python-ly

- ly/rests.py
This is related to the rest conversion wish in issue #10.
The four functions facilitate the replacement of rests (`r`), full measure rests (`R`), spacer rests (`s`) and rests by rest command (`\rest`).
As said in the issue I'm thinking in particular about changes between full measure rests and spacer rests. But I hope these can also be useful for other stuff!
> Rest editing tools

- ly/colorize.py
With `HtmlWriter.use_id_or_class()` the user now has better control
over how the  `<pre>` element is exported. I did always have to
replace this manually, which was far from convenient.
I will add the respective options to Frescobaldi too.
> Config colorize

- ly/pitch/transform.py
This may or may not be merged at this point. But this is still only very basic functionality that doesn't cover all cases. For example, the inversion function now only handles absolute pitches.
The next step would be to add a dispatcher like the `gen` class in the transpose or abs2rel in modules. In fact for `inversion` I think the exact code from the transpose module could be used (for `retrograde` I'm not sure). But instead of copy-and-pasting maybe the code itself should be on a more generic level!?? 
It is also assumed here that this can be useful on a wider user base. If LilyPond and Frescobaldi is more for engravers and transcribers than original creators that may be in doubt. In such case I could place this in the composer tools package I'm building.
> New module for transforming pitches

- ly/colorize.py
This commit improves the `melt_mapped_tokens` function so that
adjacent tokens are also melted when they are separated by spaces, e.g.
```
{
c d e
}
```
will only return one `<span class="lilypond-pitch">` item instead of three.
> colorize: "Melt" also over space characters

- ly/data/_lilypond_data.py
Added in LilyPond version 2.19.31:
http://git.savannah.gnu.org/cgit/lilypond.git/commit/?id=84ac019c437ea40b7b18ab46da1772f6db344a83
> add new context property supportNonIntegerFret

- ly/musicxml/create_musicxml.py
- ly/musicxml/ly2xml_mediator.py
- ly/musicxml/lymus2musxml.py
- ly/musicxml/xml_objs.py
I have fixed a variety of bugs I encountered while using the MusicXML export. I've also improved the export of dynamics so that one can use textual dynamics like `\cresc` and `\dim`. Some of the changes tries to correct the order of XML nodes to satisfy the MusicXML standard. There may be other ways of ensuring correct ordering that are more robust than what I suggest. Open for suggestions.
I have minimal working/non-working examples that demonstrate the bugs I've fixed, which I can provide/commit if necessary. (Are there any unit/regression tests for python-ly at the moment?)
> A variety of bug fixes and improvements for MusicXML output

- ly/cli/command.py
- ly/cli/doc.py
- ly/cli/main.py
- ly/cli/setvar.py
This pull requests adds the configuration options to the standalone script that had been implemented in general in #42
> Html options for standalone script

- ly/cli/main.py
When setting a variable in the command string it produced an
"unknown variable" error when the variable name didn't start immediately after the semicolon. This was because the "sanitizing" applied by the
split() operation wasn't applied when directly referencing `c`.
> strip() variables in command string

- bin/ly-server
- ly/server/__init__.py
- ly/server/command.py
- ly/server/doc.py
- ly/server/handler.py
- ly/server/main.py
- ly/server/options.py
- ly/server/testjson.py
Addresses #60
In its first version this server supports POST requests that trigger the ly commands just like the ly CLI script does.
The new version leaves `ly.cli` completely alone and just uses `ly.cli.setvar`. Everything else is implemented from copies of the `ly.cli` code.
For the creation of commands I have implemented a whitelist in order to prevent arbitrary "attributes" to be called.
To be done:
- Encoding problem with Python2/3 (see `command.musicxml`)
- Disambiguation of error reporting
- implementing the --timeout option (automatic shutdown)
- Add some GET routes for more interesting behaviour
- /version (return ly version)
- /stop (stop the server)
- /timeout/N (modify the timeout)
- etc?
> (New) Initial version of ly-server, an HTTP server

- ly/musicxml/create_musicxml.py
A simple fix to a crash in lilypond (python-ly -> convert-ly ->
lilypond) due to tempo being exported as a float.
> MusicXML: tempo number should be integer

- ly/musicxml/create_musicxml.py
- ly/musicxml/ly2xml_mediator.py
- ly/musicxml/lymus2musxml.py
- ly/musicxml/xml_objs.py
- tests/test_xml.py
- tests/test_xml_files/break.ly
- tests/test_xml_files/break.xml
Feature implementation in order to solve #30.
> \break export to MusicXML

- ly/musicxml/create_musicxml.py
- ly/musicxml/ly2xml_mediator.py
- ly/musicxml/lymus2musxml.py
- ly/musicxml/xml_objs.py
- tests/test_xml.py
- tests/test_xml_files/markup.ly
- tests/test_xml_files/markup.xml
It is still a work in progress. Right now it only works with a single word after \markup, as in the markup.ly test file.
> MusicXML: \markup export

- ly/musicxml/create_musicxml.py
- ly/musicxml/ly2xml_mediator.py
- ly/musicxml/lymus2musxml.py
- ly/musicxml/xml_objs.py
- tests/test_xml.py
- tests/test_xml_files/mark.ly
- tests/test_xml_files/mark.xml
First attempt to support \mark feature.
By now it is only able to export the following syntax: '\mark \ default' and '\mark' and add marks from 'A' to 'Z'.
> MusicXML: \mark export

- ly/musicxml/ly2xml_mediator.py
- ly/musicxml/xml_objs.py
- tests/test_xml.py
- tests/test_xml_files/no_barcheck.ly
- tests/test_xml_files/no_barcheck.xml
Solution to export measures without the help of explicit barchecks `|`.
The @PeterBjuhr solution gave me a good idea about how to do this, but it fails when time signature changes along the score.
To do so I chose to 'create' the measures inside the mediator instead of inside `xml_objs.py`
It has to be refined yet, mainly because it always leave a blank measure at the end of the score.
> MusicXML: Fix barcheck need

- ly/musicxml/create_musicxml.py
- ly/musicxml/ly2xml_mediator.py
- ly/musicxml/xml_objs.py
Any tagline (including `""` and `##f`) has been exported to a <tagline />
tag within `<identification>`. This is invalid MusicXML, and I think it should be generally reconsidered to simply pump unrecognized header items to
score.info[name].
For "tagline" this commit fixes the behaviour by treating a tagline as a
"rights" tag.
According to the specification one or multiple rights tags can be present,
and if more than one is present each must have an (arbitrary) attribute.
> MusicXML export: Properly handle tagline and copyright

- ly/musicxml/ly2xml_mediator.py
- ly/musicxml/lymus2musxml.py
- ly/musicxml/xml_objs.py
- tests/test_xml.py
- tests/test_xml_files/merge_voice_slurs.ly
- tests/test_xml_files/merge_voice_slurs.xml
These changes should make it possible keep slurs over multiple bars and merge other voices with slurs in a ScoreSection.
Tests are added, but the test script must be modified (not pushed here) in order to run on my machine (Ubuntu 16.10, python 3.5).
> MusicXML: Fix slurs over bars and voices

- ly/document.py
I think it is more straightforward to have `next()` and `previous()` methods for getting to the next token than using `forward()` and interrupt immediately.
The methods handle both requests limited to the current line and document-wide.
The `forward()` methods etc. have been updated to use the new methods.
I thought this is a more natural approach when investigating the context of the current cursor position in Frescobaldi.
> next() and previous() methods for ly.document.Runner()

- ly/indent.py
Bring Scheme indentation closer to standard Scheme indentation (as found in GNU Emacs), by using the standard indentation style for all tokens that aren't special cases.
Currently, `python-ly` treats some Scheme tokens as special cases (`if`, `and`, `or`, etc.), and indents them like this, aligning the second and third sub-expression with the first:
(something first-subexpression
second-subexpression
third-subexpression)
But that is actually the standard Scheme indentation style that should be used by default.  The special cases (including tokens like `define`) are indented more like this:
(something first-subexpression
second-subexpression
third-subexpression)
So the code in this PR uses the standard indentation style by default for all tokens that aren't special cases, and treats the …
> Improve indentation of Scheme code

- ly/lex/lilypond.py
This makes the handling of dashes more correct.  For example, \set
should not be recognized as a builtin command in \set-abcd.
Fixes frescobaldi/frescobaldi#1400
> Use identifier_end_re instead of \b where appropriate

- ly/lex/lilypond.py
- ly/words.py
Fixes #168 
Missing commands and keywords were added to ly/words.py so that they will highlight and autocomplete.  A new dynamic, "n", and a new unit of measure, "bp", were added to regexes in ly/lex/lilypond.py.
> Add missing commands and keywords

- CHANGELOG.md
- README.rst
- ly/pkginfo.py
- tests/test_xml.py
- tests/test_xml_files/break.xml
- tests/test_xml_files/breathe.xml
- tests/test_xml_files/church_modes.xml
- tests/test_xml_files/dynamics.xml
- tests/test_xml_files/full_bar_rest.xml
- tests/test_xml_files/glissando.xml
- tests/test_xml_files/mark.xml
- tests/test_xml_files/markup.xml
- tests/test_xml_files/merge_voice.xml
- tests/test_xml_files/merge_voice_slurs.xml
- tests/test_xml_files/no_barcheck.xml
- tests/test_xml_files/partial.xml
- tests/test_xml_files/stem.xml
- tests/test_xml_files/tie.xml
- tests/test_xml_files/tuplet.xml
- tests/test_xml_files/variable.xml
I've set 13th of December as release date, as we might need some time to review again the LilyPond syntax and other stuff.
> Prepare for 0.9.9 release

- ly/musicxml/xml_objs.py
This avoids an `AttributeError` if the last object in a `ScorePart`'s `barlist` is not a `Bar`. For example, `\addlyrics` blocks are represented by simple Python `list`s rather than `Bar` objects.
Fixes #69.
> Add more robust logic to find the last Bar in a ScorePart
